In [1]:
import pandas as pd

data = {
    "Study_Hours":[1,2,3,4,5,6,7,8,9,10,11,12],
    "Attendance":[60,65,70,72,75,80,82,85,88,90,92,95],
    "Assignments":[2,3,4,5,5,6,7,7,8,8,9,10],
    "Marks":[35,40,45,50,58,65,72,78,82,88,92,96]
}

df = pd.DataFrame(data)

df.to_csv("student_performance.csv", index=False)

print("Dataset Saved Successfully")

Dataset Saved Successfully

In [2]:
import pandas as pd

df = pd.read_csv("student_performance.csv")

df.head()

   Study_Hours  Attendance  Assignments  Marks
0            1          60            2     35
1            2          65            3     40
2            3          70            4     45
3            4          72            5     50
4            5          75            5     58

In [3]:
df.tail()

    Study_Hours  Attendance  Assignments  Marks
7             8          85            7     78
8             9          88            8     82
9            10          90            8     88
10           11          92            9     92
11           12          95           10     96

In [4]:
df.shape

(12, 4)

In [5]:
df.columns

Index(['Study_Hours', 'Attendance', 'Assignments', 'Marks'], dtype='object')

In [6]:
df.dtypes

Study_Hours    int64
Attendance     int64
Assignments    int64
Marks          int64
dtype: object

In [7]:
df.describe()

       Study_Hours  Attendance  Assignments      Marks
count    12.000000   12.000000    12.000000  12.000000
mean      6.500000   79.500000     6.166667  66.750000
std       3.605551   11.172206     2.443296  21.080474
min       1.000000   60.000000     2.000000  35.000000
25%       3.750000   71.500000     4.750000  48.750000
50%       6.500000   81.000000     6.500000  68.500000
75%       9.250000   88.500000     8.000000  83.500000
max      12.000000   95.000000    10.000000  96.000000

In [8]:
X = df[["Study_Hours","Attendance","Assignments"]]

y = df["Marks"]

print("Features")

print(X)

print("\nLabel")

print(y)

Features
    Study_Hours  Attendance  Assignments
0             1          60            2
1             2          65            3
2             3          70            4
3             4          72            5
4             5          75            5
5             6          80            6
6             7          82            7
7             8          85            7
8             9          88            8
9            10          90            8
10           11          92            9
11           12          95           10

Label
0     35
1     40
2     45
3     50
4     58
5     65
6     72
7     78
8     82
9     88
10    92
11    96
Name: Marks, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("X_train:", X_train.shape)

print("X_test:", X_test.shape)

print("y_train:", y_train.shape)

print("y_test:", y_test.shape)

X_train: (9, 3)
X_test: (3, 3)
y_train: (9,)
y_test: (3,)

In [10]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

print("Coefficients")

print(model.coef_)

print("\nIntercept")

print(model.intercept_)

Coefficients
[ 3.45487968  1.34491979 -2.40274064]

Intercept
-48.100601604278054

In [11]:
new_students = pd.DataFrame({
    "Study_Hours":[5,8,12],
    "Attendance":[80,90,95],
    "Assignments":[5,8,10]
})

predictions = model.predict(new_students)

print(predictions)

[64.75367647 81.35929144 97.09792781]

In [12]:
pred = model.predict(X_test)

comparison = pd.DataFrame({
    "Actual Marks": y_test,
    "Predicted Marks": pred
})

comparison["Difference"] = abs(
    comparison["Actual Marks"] -
    comparison["Predicted Marks"]
)

comparison

    Actual Marks  Predicted Marks  Difference
10            92        92.011029    0.011029
9             88        88.269051    0.269051
0             35        31.243984    3.756016

In [13]:
comparison.loc[
comparison["Difference"].idxmax()
]

Actual Marks       35.000000
Predicted Marks    31.243984
Difference          3.756016
Name: 0, dtype: float64

In [14]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score

mae = mean_absolute_error(y_test, pred)

r2 = r2_score(y_test, pred)

print("MAE =", mae)

print("R2 =", r2)

MAE = 1.3453654188948245
R2 = 0.9929962957709836

In [15]:
import plotly.express as px

fig = px.scatter(
    df,
    x="Study_Hours",
    y="Marks",
    title="Study Hours vs Marks"
)

fig.show()

In [16]:
fig = px.scatter(
    df,
    x="Attendance",
    y="Marks",
    hover_data=df.columns,
    title="Attendance vs Marks"
)

fig.show()

In [17]:
fig = px.scatter(
    df,
    x="Assignments",
    y="Marks",
    color="Assignments",
    title="Assignments vs Marks"
)

fig.show()

In [18]:
fig = px.scatter(
    df,
    x="Study_Hours",
    y="Marks",
    trendline="ols",
    title="Regression Line Visualization"
)

fig.show()

In [19]:
future = pd.DataFrame({
    "Study_Hours": range(1,16),
    "Attendance":[85]*15,
    "Assignments":[7]*15
})

future_pred = model.predict(future)

trend = pd.DataFrame({
    "Study_Hours": range(1,16),
    "Predicted_Marks": future_pred
})

fig = px.line(
    trend,
    x="Study_Hours",
    y="Predicted_Marks",
    title="Predicted Marks Trend"
)

fig.show()

In [20]:
from google.colab import files

files.download("student_performance.csv")

**Student Research Activity**

1. What is Machine Learning?
Machine Learning is a branch of Artificial Intelligence (AI) that enables computers to learn from data and make decisions without being explicitly programmed for every task. Instead of following fixed instructions, machine learning systems identify patterns in data and use those patterns to make predictions or decisions. For example, when a streaming platform recommends movies or when an email service filters spam messages, machine learning is being used. The process usually involves collecting data, preparing it, training a model, testing its performance, and making predictions. Machine learning is useful because it can handle large amounts of data and improve over time as more information becomes available. Today, machine learning is used in many fields such as healthcare, education, finance, transportation, and social media. It helps organizations solve problems, automate tasks, and make better decisions based on data.

2. What is Linear Regression?
Linear Regression is one of the simplest and most widely used machine learning algorithms. It is used to predict a continuous numerical value based on one or more input features. The algorithm works by finding the best-fit line that represents the relationship between the input variables and the target variable. For example, in this assignment, Linear Regression is used to predict student marks based on study hours, attendance, and assignments completed. The model learns how these factors influence marks and then uses that relationship to make predictions for new data. Linear Regression is easy to understand and interpret, making it a good starting point for beginners in machine learning. It is commonly used in business, education, finance, and sales forecasting. By analyzing trends in data, Linear Regression helps organizations make informed decisions and estimate future outcomes accurately.

3. What are Features?
Features are the input variables used by a machine learning model to make predictions. They contain the information that helps the model understand patterns in the data. In this assignment, the features are Study_Hours, Attendance, and Assignments. These values provide information about a student's academic behavior. The machine learning model uses these features to predict the student's marks. Choosing the right features is important because they directly affect the accuracy of the model. Features can be numerical values, categories, text, or other types of data depending on the problem being solved. For example, in a house price prediction model, features could include the size of the house, number of bedrooms, and location. Good features help the model learn meaningful relationships, while poor features may reduce the quality of predictions. Therefore, feature selection is an important step in the machine learning workflow.

4. What are Labels?
Labels are the output values that a machine learning model tries to predict. They represent the correct answers in the dataset and are used during training so the model can learn relationships between inputs and outputs. In this assignment, the label is Marks because it is the value being predicted. The features provide information, while the label provides the expected result. During training, the model compares its predictions with the actual labels and adjusts itself to improve accuracy. Labels are also called target variables or dependent variables. In different machine learning projects, labels can represent different things. For example, in a salary prediction model, the label would be Salary. In a house price prediction model, the label would be House Price. Labels play a crucial role because they guide the learning process and help the model understand what it should predict.

5. What is the Difference Between Training Data and Testing Data?
Training data and testing data are two important parts of the machine learning process. Training data is used to teach the model and help it learn patterns from the dataset. During training, the algorithm studies the relationship between features and labels. Testing data is used after training to evaluate how well the model performs on new, unseen data. The testing data is not shown to the model during training, making it a fair way to measure performance. In this assignment, the dataset was divided into 80% training data and 20% testing data. This means most of the data was used for learning, while the remaining data was used for evaluation. The purpose of this split is to ensure that the model does not simply memorize the data. A good machine learning model should perform well on both training and testing data, showing that it can generalize to new situations.

6. Where is Machine Learning Used in Real Life?
Machine Learning is used in many real-life applications across different industries. In healthcare, it helps doctors detect diseases, analyze medical images, and recommend treatments. In finance, machine learning is used for fraud detection, risk analysis, and stock market predictions. Social media platforms use machine learning to recommend content, identify harmful posts, and personalize user experiences. Online shopping websites use it to suggest products based on customer preferences and browsing history. Navigation apps use machine learning to predict traffic conditions and suggest the fastest routes. In education, machine learning can analyze student performance and provide personalized learning recommendations. Voice assistants, facial recognition systems, and language translation tools also rely on machine learning. As technology continues to advance, machine learning is becoming increasingly important in solving complex problems, improving efficiency, and helping organizations make data-driven decisions.

In [22]:
import pandas as pd

salary_data = {
    "Experience":[1,2,3,4,5,6,7,8,9,10,
                  11,12,13,14,15,16,17,18,19,20],

    "Education":[1,1,1,2,2,2,3,3,3,3,
                 3,4,4,4,4,5,5,5,5,5],

    "Certifications":[0,1,1,1,2,2,2,3,3,3,
                      4,4,4,5,5,5,6,6,6,7],

    "Salary":[25000,28000,32000,36000,40000,
              45000,50000,55000,60000,65000,
              70000,75000,80000,85000,90000,
              95000,100000,105000,110000,115000]
}

salary_df = pd.DataFrame(salary_data)

salary_df

    Experience  Education  Certifications  Salary
0            1          1               0   25000
1            2          1               1   28000
2            3          1               1   32000
3            4          2               1   36000
4            5          2               2   40000
5            6          2               2   45000
6            7          3               2   50000
7            8          3               3   55000
8            9          3               3   60000
9           10          3               3   65000
10          11          3               4   70000
11          12          4               4   75000
12          13          4               4   80000
13          14          4               5   85000
14          15          4               5   90000
15          16          5               5   95000
16          17          5               6  100000
17          18          5               6  105000
18          19          5               6  110000
19          20          5               7  115000

In [23]:
X = salary_df[
    ["Experience","Education","Certifications"]
]

y = salary_df["Salary"]

print(X.head())
print(y.head())

   Experience  Education  Certifications
0           1          1               0
1           2          1               1
2           3          1               1
3           4          2               1
4           5          2               2
0    25000
1    28000
2    32000
3    36000
4    40000
Name: Salary, dtype: int64

In [24]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Data Shape:", X_train.shape)
print("Testing Data Shape:", X_test.shape)

Training Data Shape: (16, 3)
Testing Data Shape: (4, 3)

In [25]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

print("Model Trained Successfully")

Model Trained Successfully

In [26]:
new_employee = pd.DataFrame({
    "Experience":[8],
    "Education":[3],
    "Certifications":[4]
})

prediction = model.predict(new_employee)

print("Predicted Salary:", prediction[0])

Predicted Salary: 54680.84345961401