In [1]:
import pandas as pd

data = {
    "Study_Hours":[1,2,3,4,5,6,7,8,9,10,11,12],
    "Attendance":[60,65,70,72,75,80,82,85,88,90,92,95],
    "Assignments":[2,3,4,5,5,6,7,7,8,8,9,10],
    "Marks":[35,40,45,50,58,65,72,78,82,88,92,96]
}

df = pd.DataFrame(data)

df.to_csv("student_performance.csv", index=False)

print("Dataset Saved Successfully")

Dataset Saved Successfully

In [2]:
import pandas as pd

df = pd.read_csv("student_performance.csv")

df.head()

   Study_Hours  Attendance  Assignments  Marks
0            1          60            2     35
1            2          65            3     40
2            3          70            4     45
3            4          72            5     50
4            5          75            5     58

In [3]:
df.tail()

    Study_Hours  Attendance  Assignments  Marks
7             8          85            7     78
8             9          88            8     82
9            10          90            8     88
10           11          92            9     92
11           12          95           10     96

In [4]:
df.shape

(12, 4)

In [5]:
df.columns

Index(['Study_Hours', 'Attendance', 'Assignments', 'Marks'], dtype='object')

In [6]:
df.dtypes

Study_Hours    int64
Attendance     int64
Assignments    int64
Marks          int64
dtype: object

In [7]:
df.describe()

       Study_Hours  Attendance  Assignments      Marks
count    12.000000   12.000000    12.000000  12.000000
mean      6.500000   79.500000     6.166667  66.750000
std       3.605551   11.172206     2.443296  21.080474
min       1.000000   60.000000     2.000000  35.000000
25%       3.750000   71.500000     4.750000  48.750000
50%       6.500000   81.000000     6.500000  68.500000
75%       9.250000   88.500000     8.000000  83.500000
max      12.000000   95.000000    10.000000  96.000000

In [8]:
X = df[["Study_Hours","Attendance","Assignments"]]

y = df["Marks"]

print("Features")

print(X)

print("\nLabel")

print(y)

Features
    Study_Hours  Attendance  Assignments
0             1          60            2
1             2          65            3
2             3          70            4
3             4          72            5
4             5          75            5
5             6          80            6
6             7          82            7
7             8          85            7
8             9          88            8
9            10          90            8
10           11          92            9
11           12          95           10

Label
0     35
1     40
2     45
3     50
4     58
5     65
6     72
7     78
8     82
9     88
10    92
11    96
Name: Marks, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("X_train:", X_train.shape)

print("X_test:", X_test.shape)

print("y_train:", y_train.shape)

print("y_test:", y_test.shape)

X_train: (9, 3)
X_test: (3, 3)
y_train: (9,)
y_test: (3,)

In [10]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

print("Coefficients")

print(model.coef_)

print("\nIntercept")

print(model.intercept_)

Coefficients
[ 3.45487968  1.34491979 -2.40274064]

Intercept
-48.100601604278054

In [11]:
new_students = pd.DataFrame({
    "Study_Hours":[5,8,12],
    "Attendance":[80,90,95],
    "Assignments":[5,8,10]
})

predictions = model.predict(new_students)

print(predictions)

[64.75367647 81.35929144 97.09792781]

In [12]:
pred = model.predict(X_test)

comparison = pd.DataFrame({
    "Actual Marks": y_test,
    "Predicted Marks": pred
})

comparison["Difference"] = abs(
    comparison["Actual Marks"] -
    comparison["Predicted Marks"]
)

comparison

    Actual Marks  Predicted Marks  Difference
10            92        92.011029    0.011029
9             88        88.269051    0.269051
0             35        31.243984    3.756016

In [13]:
comparison.loc[
comparison["Difference"].idxmax()
]

Actual Marks       35.000000
Predicted Marks    31.243984
Difference          3.756016
Name: 0, dtype: float64

In [14]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score

mae = mean_absolute_error(y_test, pred)

r2 = r2_score(y_test, pred)

print("MAE =", mae)

print("R2 =", r2)

MAE = 1.3453654188948245
R2 = 0.9929962957709836

In [15]:
import plotly.express as px

fig = px.scatter(
    df,
    x="Study_Hours",
    y="Marks",
    title="Study Hours vs Marks"
)

fig.show()

In [16]:
fig = px.scatter(
    df,
    x="Attendance",
    y="Marks",
    hover_data=df.columns,
    title="Attendance vs Marks"
)

fig.show()

In [17]:
fig = px.scatter(
    df,
    x="Assignments",
    y="Marks",
    color="Assignments",
    title="Assignments vs Marks"
)

fig.show()

In [18]:
fig = px.scatter(
    df,
    x="Study_Hours",
    y="Marks",
    trendline="ols",
    title="Regression Line Visualization"
)

fig.show()

In [19]:
future = pd.DataFrame({
    "Study_Hours": range(1,16),
    "Attendance":[85]*15,
    "Assignments":[7]*15
})

future_pred = model.predict(future)

trend = pd.DataFrame({
    "Study_Hours": range(1,16),
    "Predicted_Marks": future_pred
})

fig = px.line(
    trend,
    x="Study_Hours",
    y="Predicted_Marks",
    title="Predicted Marks Trend"
)

fig.show()